### ISSUE TITLE
Rename fecfile-ImageGenerator repo

### ISSUE THREAD

**Issue by rfultz** [fecgov/fecfile-ImageGenerator#24]
#Consideration
To keep things consistent with the rest of the FEC repos, could we rename this repo to fecfile-image-generator (instead of a capitals I & V, and add a `-`)?

#Possible complications
Would this break anything? -- We renamed the fecfile-online repo to fecfile-web-app on Jan. 18 and have not uncovered any problems related to the name change yet. ZenHub handled the change gracefully.

**Acceptance Criteria**

- [x]  The name of the image generator GitHub repo is: fecfile-image-generator

**Comment by lbeaufort** [comment]
Repo has been renamed: https://github.com/fecgov/fecfile-image-generator no code review required. Moving to QA.

**Comment by WiseQA** [comment]
Verified renaming of Repo changed to fecfile-image-generator:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/831d350d-e796-4188-a149-1b7cef1177a5)

QA review completed.  Moved to Stage Ready.
