### ISSUE TITLE
Deploy fecfile-image-generator to cloud.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-ImageGenerator#28]
Set up deployment of fecfile-image-generator to Cloud.gov

**Issues that will/may need addressing**
- Use of AWS SQS service. Queue service will need an equivalent in Cloud.gov.
- Use of local file system to write temporary files. Need to verify local file system is only used briefly as a local cache per https://12factor.net/processes.
- Installation of PDFtk binary on server. https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/
- Is the wkhtmltopdf tool still being used or was it replaced by PDFtk?

**Note**
This ticket does not include set up of an AWS SQS alternative service.

**Acceptance Criteria**
Responses from the server when these URLs are entered into a browser address after CircleCI deploys to the space:
- [x] Development server: https://fecfile-image-generator-dev.app.cloud.gov/v1/app-name
- [x] Stage server: https://fecfile-image-generator-stage.app.cloud.gov/v1/app-name
- [x] Production server: https://fecfile-image-generator-prod.app.cloud.gov/v1/app-name

**QA**
This ticket is to simply get the code to deploy to the Cloud.gov environments. There are known issues with the actual code which are to be addressed in future tickets. To verify the code has been deployed, you can view "fecfile-image-generator" on a page in the links in the Acceptance Criteria above.

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/9/22:** Does not include setup of AWS SQS. Pointed at 13.

**Comment by WiseQA** [comment]
Verified responses from the server when these URLs denoted in the Acceptance Criteria are entered into a browser address.

DEV Server:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/10c5bf85-1819-4c38-9733-990d761ef374)

Stage Server:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9f3edfe9-39cd-4f4e-97ee-1e5abc17bcc9)

PROD Server:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0fa19b77-a73e-4858-bfb6-9732c59bd586)

QA review completed.  Moved to Stage Ready.
