### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-ImageGenerator#34]
Python linting errors remain (see [CircleCI output](https://app.circleci.com/pipelines/github/fecgov/fecfile-image-generator/38/workflows/150b40b0-47ee-4961-b9e9-78889bb950bc/jobs/76)) - we should fix them so we don't create new problems.

**Comment by mjtravers** [comment]
Image Generator repo is OBE now that the project will leverage the FEC Web Services.
Closing ticket.
