### ISSUE TITLE
Make deploy conditional on other automated checks

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-ImageGenerator#35]
Code shouldn't deploy until automated checks pass.

### Business Reason ### 

As a [role], I will be able to [blank] so that I can [business reason]

### Acceptance Criteria ### 

**If** [precedent]
**When** [action]
**Then** [result]

**Comment by mjtravers** [comment]
This ticket has been completed in a previous ticket. See CircleCI config.yml script for details. OBE and closing ticket.
